{
    "openapi": "3.0.0",
    "info": {
        "title": "API Cadastro de Usu√°rios e Times",
        "description": "This is an Api Users and Teams",
        "version": "2.0.0",
        "contact": {
            "email": "macamagolf@gmail.com"
        }
    },
    "paths": {
        "/createUser": {
            "post": {
                "tags": ["Users"],
                "summary": "Create a User",
                "description": "Create a New User",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "user_id": {
                                        "type": "string"
                                    },
                                    "username": {
                                        "type": "string"
                                    },
                                    "userAvatar": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "created_at": {
                                        "type": "string"
                                    }
                                }
                            },
                            "description": "Mandatory fields for creating a User",
                            "example": {
                                "username": "username sample",
                                "userAvatar": "useravatar sample",
                                "email": "email sample",
                                "password": "password sample"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "user_id": {
                                                "type": "string"
                                            },
                                            "username": {
                                                "type": "string"
                                            },
                                            "userAvatar": {
                                                "type": "string"
                                            },
                                            "email": {
                                                "type": "string"
                                            },
                                            "password": {
                                                "type": "string"
                                            },
                                            "created_at": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "example": [
                                    {
                                        "user_id": "5636ab39-acd2-4224-a5ee-f48e8eedf99e",
                                        "username": "username sample",
                                        "userAvatar": "useravatar sample",
                                        "email": "email sample",
                                        "password": "password sample",
                                        "created_at": "2022-06-30T02:34:35.623Z"
                                    }
                                ]
                            }
                        }
                    },
                    "404": {
                        "description": "User Already Exists !"
                    }
                }
            }
        },
        "/sessions": {
            "post": {
                "tags": ["Users"],
                "summary": "Authenticate User",
                "description": "Authenticate User",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "description": "Mandatory fields for autheticate a User",
                            "example": {
                                "email": "user email",
                                "password": "user password"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "user": {
                                                "user_id": {
                                                    "type": "string"
                                                },
                                                "username": {
                                                    "type": "string"
                                                },
                                                "email": {
                                                    "type": "string"
                                                }
                                            },
                                            "token": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "user": {
                                        "user_id": "7597ba1d-689b-4293-a76e-46e684b0d2ec",
                                        "email": "user email",
                                        "password": "user password"
                                    },
                                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOiI3NTk3YmExZC02ODliLTQyOTMtYTc2ZS00NmU2ODRiMGQyZWMiLCJ1c2VybmFtZSI6IlNldSBNYWRydWdhIiwidXNlckF2YXRhciI6Ik1hZHJ1Z3VpyZWMiLCJ1c2VybmFtZSI6IlNldSBNYWRydWdhIiwidXNlckF2YXRhciI6Ik1hZHJ1Z3VpyZWMiLCJ1c2VybmFtZSI6IlNldSBNYWRydWdhIiwidXNlckF2YXRhciI6Ik1hZHJ1Z3VpyZWMiLCJ1c2VybmFtZSI6IlNldSBNYWRy"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Password incorrect!"
                    },
                    "404": {
                        "description": "Email incorrect!"
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "tags": ["Users"],
                "summary": "List Specif User",
                "description": "List Specif User",
                "security": [
                    { "bearerAuth": [] }
                ],
                "parameters": [
                    {
                        "in": "query",
                        "name": "user_id",
                        "required": true,
                        "schema": {
                            "type": "string",
                            "format": "uuid"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "user_id": {
                                                "type": "string"
                                            },
                                            "username": {
                                                "type": "string"
                                            },
                                            "userAvatar": {
                                                "type": "string"
                                            },
                                            "email": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "user_id": "bb16df2b-462a-483e-8257-f82924a19dea",
                                    "username": "username sample",
                                    "userAvatar": "useravatar sample",
                                    "email":"user email"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "JWT token is missing!"
                    },
                    "404": {
                        "description": "User Not Found!"
                    },
                    "409": {
                        "description": "Invalid token!"
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}
